[[redirects]]
  from = "/restaurants/*"
  to = "/restaurants/:splat.html"
  status = 200
[[redirects]]
  from = "/bars/*"
  to = "/bars/:splat.html"
  status = 200
[[redirects]]
from = "/what-are-you-looking-for.html"
to = "/what-are-you-looking-for"
status = 200
[[redirects]]
from = "/neighborhoods.html"
to = "/neighborhoods"
status = 200
[[redirects]]
from = "/food/index.html"
to = "/food"
status = 200
[[redirects]]
from = "/drink/index.html"
to = "/drinks"
status = 200
[[headers]]
for = "/*"
[headers.values]
Cross-Origin-Opener-Policy = "same-origin-allow-popups"
Cross-Origin-Embedder-Policy = "unsafe-none"